### ISSUE TITLE
symfony 4 ?

### ISSUE THREAD

**Issue by mediafigaro** [doctrine/DoctrineCouchDBBundle#58]
Hello, would this bundle be used with SF4 :/ ?

**Comment by silverbackdan** [comment]
I had the same question, I forked and worked on this bundle so that all the tests are passing for me. There is no continuous integration file as far as I can see (e.g. travis) but I've tried to be careful to maintain backwards compatibility except for PHP which had a minimum of 5.3.2 and in my PR has a minimum of 5.5.

I haven't used this updated version myself yet, I'm just about to, but if you'd like to before the conversations are completed and the PR is merged then it is here:
https://github.com/silverbackdan/DoctrineCouchDBBundle

**Comment by mediafigaro** [comment]
thanks a lot !!!

**Comment by silverbackdan** [comment]
No worries. FYI the bundle does not support the new SF4 file structure. This config will sort the mapping though:
```yaml
doctrine_couch_db:
    client:
        connections:
            default:
                dbname: products
                host: '%env(COUCHDB_HOST)%'
                user: '%env(COUCHDB_USER)%'
                password: '%env(COUCHDB_PASSWORD)%'
    odm:
        document_managers:
            default:
                mappings:
                    App:
                        type: annotation
                        dir: '%kernel.project_dir%/src/CouchDocument'
                        is_bundle: false
                        prefix: App\CouchDocument
                        alias: App
                auto_mapping: true

```
